databases:
  - name: universo-dev-db
    databaseName: universo_dev
    user: universo_dev_user
    plan: free

services:
  - type: web
    name: universo-dev
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:uNGbpjhpbWDPC1aqom6Rs0+jODbAos8y8JzmQeGTiEs=
      - key: APP_URL
        sync: false
      - key: ASSET_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: universo-dev-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: universo-dev-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: universo-dev-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: universo-dev-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: universo-dev-db
          property: password
